### PR TITLE
Fix/docker 38

### LINKED ISSUE #38: Docker is broken right now because the node version is too old
Moved this issue here because we need to fix this repo's Dockerfile to fix it... currently working on that fix

### PR DESCRIPTION
**Pull request by rafibarash**
Fixes #38 

## Features

- Changed config file to environment variables. This allows the honeyclient to work seamlessly both locally and with docker-compose
- Updated Dockerfile to work with Node 12, yara, and tesseract

### CODE REVIEW

File: src/utils/tickets.js [hunk 1]
```diff
@@ -30,28 +39,26 @@ const getMalwareMatches = async URLs => {
...
+      console.log('No Malware found');
+      return [];
+    } else {
+      console.log('Malware found');
+      console.log(json.matches);
+      return json.matches;
+    }
+  } catch (err) {
+    console.error(error);
+    throw Error(err.message);
```
Comment (williamtdr) [inline src/utils/tickets.js]: In the long term, we probably want to catch errors during HC processing, and change states (right now there’s no way to retry, or have a processed ticket for which some subtasks errored).

Comment (rafibarash) [reply src/utils/tickets.js]: Yeah we definitely have to do some error handling refactoring across the board when we do that big refactor
